### ISSUE TITLE
Diff options disappear after clicking on split diff

### ISSUE THREAD

**Issue by johnkhughes** [JetpackDuba/Gitnuro#171] opened 2023-10-13 11:29 UTC
**Describe the bug**
Clicking on the "split diff" button causes all the diff buttons to disappear permanently so you cannot change back to the unified diff view. The only way to get the unified view back is to edit `~/.var/app/com.jetpackduba.Gitnuro/config/gitnuro/.java/.userPrefs/GitnuroConfig/prefs.xml` to remove the diff view setting.

**To Reproduce**

1. Click on a commit
2. Click on a file to view the diff
3. Click on the "split diff" button
4. The diff buttons disappear

**Expected behavior**
The buttons should not disappear so you can switch back to the unified diff view.

**Screenshots**
Before, while the unified diff is visible:

![gitnuro-unified](https://github.com/JetpackDuba/Gitnuro/assets/1375434/1d62278c-584e-417c-a990-13e95f1b7468)

After, while the split diff is visible:

![gitnuro-split](https://github.com/JetpackDuba/Gitnuro/assets/1375434/67f4de93-3451-4458-83df-f70337bd9e61)

**Desktop (please complete the following information):**

- OS: Linux Mint
- Version 21.1
- Gitnuro 1.3.0 installed via Flatpak

**Comment by JetpackDuba** [comment] 2023-10-13 11:37
Hey! Duplicate of https://github.com/JetpackDuba/Gitnuro/issues/169

Will be fixed in 1.3.1

**Closed by JetpackDuba** 2023-10-13 11:37 UTC
Labels: bug
