### ISSUE TITLE
[Bug] file diff button disapper

### ISSUE THREAD

**Issue by lingfengyu-dreaming** [JetpackDuba/Gitnuro#178] opened 2023-10-24 10:38 UTC
**Describe the bug**
when i open a file to show the diff, i found it is unity view, and i want to change it to split view, and i click the button on the top to change the view, then the window change to split view, then the button disapper.(in screenshot)

**To Reproduce**

1. Open a file in previous commit
2. Click on the file to open the diff
3. Click on the button to change to split view
4. See error, the button disapper

**Expected behavior**
the button stay there and highlight the chosen one

**Screenshots**
![image](https://github.com/JetpackDuba/Gitnuro/assets/61617417/57a30791-f72d-4943-a827-418778103aa8)

**Desktop (please complete the following information):**

- OS: Windows 11 23h2(22635.2486beta)
- Version 1.3.0

**Comment by JetpackDuba** [comment] 2023-10-24 10:59
Hey! Duplicate of https://github.com/JetpackDuba/Gitnuro/issues/169

Will be fixed in 1.3.1

There is a workaround in the mentioned issue, you will need to adapt the path for windows.

**Closed by JetpackDuba** 2023-10-24 10:59 UTC
Labels: bug
