### ISSUE TITLE
org.eclipse.jgit.api.errors.TransportException: Failure updating tracking ref refs/remotes/<remote-ref>: Missing unknown <sha1>

### ISSUE THREAD

**Issue by Mingun** [JetpackDuba/Gitnuro#249] opened 2024-11-12 06:07 UTC
**Describe the bug**
I noted that attempt to fetch data ends with an error which, it seems, not actually an error, but and indication that local repository does not have commits that can be fetched from remote. An example repository and corresponding event log for **Fetch all** is attached.

**To Reproduce**

1. Open attached repository [compiler.zip](https://github.com/user-attachments/files/17711766/compiler.zip)
2. Click on 'Fetch all' command in Pull drop-down
3. See error:
    ![Fetch all](https://github.com/user-attachments/assets/b5c24c22-e4ef-4cfd-a15c-258105a828bf)
4. Check error log: [gitnuro.log](https://github.com/user-attachments/files/17711773/gitnuro.log), see the errors like
	```
	org.eclipse.jgit.api.errors.TransportException: Failure updating tracking ref refs/remotes/mingun/538: Missing unknown 65b44132d23e9291b81a49d46d25c7fb5bac7047
		at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:249)
		at com.jetpackduba.gitnuro.git.remote_operations.FetchAllRemotesUseCase$invoke$2$1.invokeSuspend(FetchAllRemotesUseCase.kt:45)
		at com.jetpackduba.gitnuro.git.remote_operations.FetchAllRemotesUseCase$invoke$2$1.invoke(FetchAllRemotesUseCase.kt)
		at com.jetpackduba.gitnuro.git.remote_operations.FetchAllRemotesUseCase$invoke$2$1.invoke(FetchAllRemotesUseCase.kt)
		at com.jetpackduba.gitnuro.git.remote_operations.HandleTransportUseCase.invoke(HandleTransportUseCase.kt:40)
		at com.jetpackduba.gitnuro.git.remote_operations.FetchAllRemotesUseCase$invoke$2.invokeSuspend(FetchAllRemotesUseCase.kt:25)
		at com.jetpackduba.gitnuro.git.remote_operations.FetchAllRemotesUseCase$invoke$2.invoke(FetchAllRemotesUseCase.kt)
		at com.jetpackduba.gitnuro.git.remote_operations.FetchAllRemotesUseCase$invoke$2.invoke(FetchAllRemotesUseCase.kt)
		at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:61)
		at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:163)
		at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
		at com.jetpackduba.gitnuro.git.remote_operations.FetchAllRemotesUseCase.invoke(FetchAllRemotesUseCase.kt:20)
		at com.jetpackduba.gitnuro.viewmodels.GlobalMenuActionsViewModel$fetchAll$1.invokeSuspend(GlobalMenuActionsViewModel.kt:59)
		at com.jetpackduba.gitnuro.viewmodels.GlobalMenuActionsViewModel$fetchAll$1.invoke(GlobalMenuActionsViewModel.kt)
		at com.jetpackduba.gitnuro.viewmodels.GlobalMenuActionsViewModel$fetchAll$1.invoke(GlobalMenuActionsViewModel.kt)
		at com.jetpackduba.gitnuro.git.TabState$safeProcessing$job$1$notification$2.invokeSuspend(TabState.kt:113)
		at com.jetpackduba.gitnuro.git.TabState$safeProcessing$job$1$notification$2.invoke(TabState.kt)
		at com.jetpackduba.gitnuro.git.TabState$safeProcessing$job$1$notification$2.invoke(TabState.kt)
		at com.jetpackduba.gitnuro.extensions.StateManagementUtilsKt.delayedStateChange(StateManagementUtils.kt:21)
		at com.jetpackduba.gitnuro.git.TabState$safeProcessing$job$1.invokeSuspend(TabState.kt:101)
		at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
		at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
		at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:111)
		at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)
		at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:585)
		at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:802)
		at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:706)
		at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:693)
	Caused by: org.eclipse.jgit.errors.TransportException: Failure updating tracking ref refs/remotes/mingun/538: Missing unknown 65b44132d23e9291b81a49d46d25c7fb5bac7047
		at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:254)
		at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:105)
		at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1482)
		at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:238)
		... 27 more
	Caused by: org.eclipse.jgit.errors.MissingObjectException: Missing unknown 65b44132d23e9291b81a49d46d25c7fb5bac7047
		at org.eclipse.jgit.internal.storage.file.WindowCursor.open(WindowCursor.java:136)
		at org.eclipse.jgit.lib.ObjectReader.open(ObjectReader.java:216)
		at org.eclipse.jgit.revwalk.RevWalk.parseAny(RevWalk.java:1144)
		at org.eclipse.jgit.transport.ReceiveCommand.updateType(ReceiveCommand.java:722)
		at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:237)
		... 30 more
	```

Note, that in the log you can see errors with two hashes, that both exists in remote repositories, but, I think, does not exist locally:
- https://github.com/kaitai-io/kaitai_struct_compiler/commit/542b24124a95f5308df625d667f8776dd023c696
- https://github.com/Mingun/kaitai_struct_compiler/commit/65b44132d23e9291b81a49d46d25c7fb5bac7047

It seems that actually this is not user-face error, but an indication that application should do some things to get the remote commits.

**Expected behavior**
Removes should be fetched without errors or error should be more descriptive if it is legitimate (I'm behind a proxy, but proxy is configured in GitNuro and in the log I do not see any transport-related errors)

**Screenshots**
See above

**Desktop (please complete the following information):**

- OS: Ubuntu 24.04.1 LTS
- Version: 1.4.2

**Comment by Mingun** [comment] 2024-11-12 06:11
Result of `git fetch --all` in the same repository:
```
$ git fetch --all
Извлечение из origin
remote: Enumerating objects: 2707, done.
remote: Counting objects: 100% (1369/1369), done.
remote: Compressing objects: 100% (210/210), done.
remote: Total 2707 (delta 849), reused 1314 (delta 818), pack-reused 1338 (from 1)
Получение объектов: 100% (2707/2707), 477.94 КиБ | 1.65 МиБ/с, готово.
Определение изменений: 100% (1041/1041), завершено с 37 локальными объектами.
Из https://github.com/kaitai-io/kaitai_struct_compiler
   2191070c..542b2412  master     -> origin/master
Извлечение из mingun
remote: Enumerating objects: 1554, done.
remote: Counting objects: 100% (1548/1548), done.
remote: Compressing objects: 100% (326/326), done.
remote: Total 1554 (delta 676), reused 1505 (delta 647), pack-reused 6 (from 1)
Получение объектов: 100% (1554/1554), 434.44 КиБ | 1.55 МиБ/с, готово.
Определение изменений: 100% (676/676), завершено с 66 локальными объектами.
Из https://github.com/Mingun/kaitai_struct_compiler
 + 05e6d354...65b44132 absolute-positions                -> mingun/absolute-positions  (принудительное обновление)
 + 696e5d7d...164ad527 annotations                       -> mingun/annotations  (принудительное обновление)
 + c231dcec...00629d9e ast-doc                           -> mingun/ast-doc  (принудительное обновление)
 + 0f862f8d...de77ec15 cs-full-name                      -> mingun/cs-full-name  (принудительное обновление)
 + 0923cb2a...279ec246 data-types                        -> mingun/data-types  (принудительное обновление)
 * [новая ветка]       fix-absolute-enums                -> mingun/fix-absolute-enums
 * [новая ветка]       fix-bad-id-test                   -> mingun/fix-bad-id-test
 + ddb646bd...30c8a29b fix-broken-doc-links              -> mingun/fix-broken-doc-links  (принудительное обновление)
 * [новая ветка]       fix-excess-id-in-path             -> mingun/fix-excess-id-in-path
 * [новая ветка]       fix-type-leaking                  -> mingun/fix-type-leaking
 * [новая ветка]       fix-type-resolution               -> mingun/fix-type-resolution
 + 7b5beb14...6b8559d0 fix-unchecked-warns               -> mingun/fix-unchecked-warns  (принудительное обновление)
 + af20f1c1...80265732 fix-validation-ownership-problems -> mingun/fix-validation-ownership-problems  (принудительное обновление)
 + 2efab63d...3bbc50eb fix-warns                         -> mingun/fix-warns  (принудительное обновление)
 + 9a303bde...307b76b5 fix-warns-call-node               -> mingun/fix-warns-call-node  (принудительное обновление)
 * [новая ветка]       fix-windows-path-problems         -> mingun/fix-windows-path-problems
 + 2dadf6c9...032007ae go-kst-fixes                      -> mingun/go-kst-fixes  (принудительное обновление)
 + ac84ac4d...9a627bd6 hex-escape-seq                    -> mingun/hex-escape-seq  (принудительное обновление)
 * [новая ветка]       human-readable                    -> mingun/human-readable
 + 33ad86b0...d72dbc18 improve-errors                    -> mingun/improve-errors  (принудительное обновление)
 + 5a95f712...4cabc528 improve-repeat                    -> mingun/improve-repeat  (принудительное обновление)
 + fb76b5de...1d4963e4 java-enums                        -> mingun/java-enums  (принудительное обновление)
 * [новая ветка]       loops                             -> mingun/loops
   2191070c..542b2412  master                            -> mingun/master
 + 67e35995...b78b4892 nim-fixes                         -> mingun/nim-fixes  (принудительное обновление)
 * [новая ветка]       passes                            -> mingun/passes
 + ea5c0e3c...b1e80647 python-construct-kst-fixes        -> mingun/python-construct-kst-fixes  (принудительное обновление)
 + 1a452838...3e1dfb98 remove-fixed-contents             -> mingun/remove-fixed-contents  (принудительное обновление)
 + 3c1abbc0...d42904ee sizeof-tests                      -> mingun/sizeof-tests  (принудительное обновление)
 + ffca8d7c...eeaf8b8b translator-tests                  -> mingun/translator-tests  (принудительное обновление)
 * [новая ветка]       valid-validation                  -> mingun/valid-validation
```

**Comment by JetpackDuba** [comment] 2024-11-12 08:27
Hey,

Yes, it's a JGit bug I've been trying to fix myself without much luck.

It's a duplicate of #123

**Closed by JetpackDuba** 2024-11-12 08:27 UTC
Labels: bug
