### ISSUE TITLE
Remote hung up unexpectedly

### ISSUE THREAD

**Issue by Etriid** [JetpackDuba/Gitnuro#87] opened 2023-02-14 10:48 UTC
Hi. After commit. Try to push and have an error "remote hung up unexpectedly". How can i resolve it. And where need to write ssh password (like this doing on this git gui , git-scm.com). Using Win7

**Comment by ProjectInfinity** [comment] 2023-02-14 11:06
Hi, could you provide more information about your setup?

As for how you enter a SSH passphrase, if the SSH key you use require a passphrase it will prompt you for it like this

![image](https://user-images.githubusercontent.com/593870/218718956-40c1dcde-3039-4d5a-a4ff-a3f40b6321ee.png)

**Comment by Etriid** [comment] 2023-02-14 11:25
i have no this window while do actions which must require ssh

**Comment by JetpackDuba** [comment] 2023-02-14 11:39
Can you start Gitnuro from the CLI snd post the logs please? I recommend using git bash to do that.

**Comment by Etriid** [comment] 2023-02-14 11:56
Where can i find logs?
(path to gitnuro - D:\Gitnuro)

**Comment by Etriid** [comment] 2023-02-14 12:11
btw. the error's screenshot 
![Безымянный](https://user-images.githubusercontent.com/68382332/218735039-c3ead634-c063-4663-b6a3-03d7e07edc48.png)

**Comment by JetpackDuba** [comment] 2023-02-14 12:33
You can get them when starting the app from a terminal

**Comment by Etriid** [comment] 2023-02-14 12:46
Nothing
![Снимок](https://user-images.githubusercontent.com/68382332/218742514-b10007c9-c2c0-490c-b0ed-56fa5bba3ec3.PNG)

**Comment by Etriid** [comment] 2023-02-14 13:21
Nothing change. All like before

**Comment by JetpackDuba** [comment] 2023-02-14 13:23
What if you `cd` into the dir where Gitnuro is and run `./Gitnuro.exe`

**Comment by Etriid** [comment] 2023-02-14 13:31
Also

**Comment by JetpackDuba** [comment] 2023-02-14 13:39
Ah wait, my bad, you don't see the output. I thought you couldn't run it.

Then... You will have to clone Gitnuro and run it. Checkout the v1.1.1 tag and get the logs.

The main branch uses a LibSSH instead of Apache SSHD used in the latest version.

Also, do you have any config set in .ssh/config ?

Not even sure if Windows 7 is supported by the libs used.

**Comment by Etriid** [comment] 2023-02-14 13:42
have no configs in .ssh/

**Comment by Etriid** [comment] 2023-02-15 04:55
okay i'll wait

**Comment by JetpackDuba** [comment] 2023-02-26 23:17
Hey sorry for the delay, can you please try this version? 
https://www.dropbox.com/s/27kb9azi8tv89sr/Gitnuro-Windows-1.2.0-portable.zip?dl=0

It uses libssh instead of the old aproach with Apache SSHD.

**Comment by JetpackDuba** [comment] 2023-03-18 16:05
Hey! Have you been able to give it a shot?

**Comment by JetpackDuba** [comment] 2023-04-10 22:00
Can you get the logs when starting gitnuro from the CLI?

**Comment by den13x** [comment] 2023-04-11 00:52
After reading the posts above, I ran git-bash.exe in it ran gitnuro.exe, the following text appeared in the console:
```
$ ./Gitnuro.exe
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
After reading prefs, got 1 tabs
SystemUtils - OS is windows 10
RESULT is 1. ERROR IS:
RESULT is 1. ERROR IS:
```
Maybe I'm not doing the log right, write how to make a log

**Comment by JetpackDuba** [comment] 2023-04-12 20:09
It's weird that you don't get a more detailed error. Anyway, reading libssh docs, result 1 is:  _SSH_AUTH_DENIED: The server doesn't accept that public key as an authentication token. Try another key or another method._

How are you managing your SSH credentials?

**Comment by den13x** [comment] 2023-04-13 23:50
Hello

I've tried other git clients:
Connect and clone repository: GitHub Desktop, Sunsetree, SmartGit.
Gitg cannot clone, error: "Failed to clone repository. error authenticating: unable to connect to agent pipe".


Tried to connect via ssh at the command line (connects fine):
```
C:\1>ssh den@192.168.1.63
den@192.168.1.63's password:
Welcome to Ubuntu 22.10 (GNU/Linux 5.19.0-38-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

12 updates can be applied immediately.
To see these additional updates run: apt list --upgradable

Last login: Thu Apr 13 23:29:09 2023 from 192.168.1.43
den@u22:~$ ls -a git-test
.  ..  file1  file2  .git
```

It clones fine through the command line:
```
c:\1\git-test-cmd>git clone ssh://den@192.168.1.63/home/den/git-test
Cloning into 'git-test'...
den@192.168.1.63's password:
remote: Enumerating objects: 4, done.
remote: Counting objects: 100% (4/4), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 4 (delta 0), reused 0 (delta 0), pack-reused 0
Receiving objects: 100% (4/4), done.
```

Then I opened the cloned repository c:\1\git-test-cmd\git-test in Gitnuro, opened normally, but Pull and Push doesn't work, show the same error: "remote hung up unexpectedly"

Maybe it is necessary to perform some kind of confirmation similar to 
![image](https://user-images.githubusercontent.com/19697835/231906365-88d84b6d-7344-414d-aa87-f54f857f53db.png)

**Comment by JetpackDuba** [comment] 2023-04-14 00:09
Hey!

How did you create the SSH key? If you are using PuTTY's Pageant, that would explain it, as it's not supported by LibSSH.

**Comment by den13x** [comment] 2023-04-14 01:13
I did not create an SSH key, I only use the password. At the command line I use ssh.exe, which is c:\Windows\System32\OpenSSH\ssh.exe, which is OpenSSH.
On Ubuntu I use the OpenSSH server

**Comment by JetpackDuba** [comment] 2023-04-14 13:11
Ah! Oke, now I'm following you.

I've done a quick change that works (at least on linux). I'll test it more and build a windows version in a few hours.

**Comment by JetpackDuba** [comment] 2023-04-15 21:41
Can you please try this @den13x ? https://www.dropbox.com/s/4ynhsaotnmgese5/Gitnuro-1.2.0-beta02_Windows.zip?dl=0

**Comment by den13x** [comment] 2023-04-16 22:16
Hello,
I checked the Clone, Pull, and Push in the new version. Everything works! Thank you!

**Comment by JetpackDuba** [comment] 2023-04-17 06:25
Thanks to you for your feedback! Keep in mind that this build is based on a beta version so some stuff is half-baked or untested, but all the major features should work out of the box.

It would be great if the original issue author, @Etriid , can give us feedback before the stable release. Otherwise I'll close the issue since it's a very generic error that may happen due to dozens of different factors, so I can't do much without logs.

**Comment by den13x** [comment] 2023-04-18 01:46
Thank you for the program, but I'm just trying different git clients, I'm just thinking about switching to git

**Comment by wicked-jane-doe** [comment] 2023-04-23 02:07
This problem is also happenning in linux (Zorin OS). Using the default ssh-agent

**Comment by JetpackDuba** [comment] 2023-04-23 12:38
Hey @wicked-jane-doe ! Yeah, it's expected. The new version adds support to the SSH agent by using LibSSH https://github.com/JetpackDuba/Gitnuro/issues/33

**Comment by JetpackDuba** [comment] 2023-05-06 14:07
As there haven't been any additional feedback, I'll close the issue. If the problem still persists with Gitnuro 1.2.0, please let me know.

**Closed by JetpackDuba** 2023-05-06 14:07 UTC
Labels: bug

**Comment by dodatw** [comment] 2023-06-16 11:02
Hi @JetpackDuba 

Is this issue fix in 1.2.1 on Mac ? I still saw "Remote hung up unexpectedly" when I do any remote action.
I use system SSH and  libssh already installed.

Thanks

**Comment by JetpackDuba** [comment] 2023-06-16 11:16
Hey @dodatw !

Can you share the logs please? The should be in `your users directory/.gitnuro` or you can see them live by starting gitnuro from the command line.

**Comment by dodatw** [comment] 2023-06-17 13:22
It look like libssh issue? 
But it say "libssh 0.10.5 is already installed and up-to-date." when I call "brew install libssh"

```
Caused by: java.lang.UnsatisfiedLinkError: Unable to load library 'ssh':
dlopen(libssh.dylib, 0x0009): tried: 'libssh.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibssh.dylib' (no such file), '/usr/lib/libssh.dylib' (no such file, not in dyld cache), 'libssh.dylib' (no such file), '/usr/local/lib/libssh.dylib' (no such file), '/usr/lib/libssh.dylib' (no such file, not in dyld cache)
dlopen(libssh.dylib, 0x0009): tried: 'libssh.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibssh.dylib' (no such file), '/usr/lib/libssh.dylib' (no such file, not in dyld cache), 'libssh.dylib' (no such file), '/usr/local/lib/libssh.dylib' (no such file), '/usr/lib/libssh.dylib' (no such file, not in dyld cache)
dlopen(/Users/rdapp/Library/Frameworks/ssh.framework/ssh, 0x0009): tried: '/Users/rdapp/Library/Frameworks/ssh.framework/ssh' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/rdapp/Library/Frameworks/ssh.framework/ssh' (no such file), '/Users/rdapp/Library/Frameworks/ssh.framework/ssh' (no such file), '/Library/Frameworks/ssh.framework/ssh' (no such file), '/System/Library/Frameworks/ssh.framework/ssh' (no such file, not in dyld cache)
dlopen(/Library/Frameworks/ssh.framework/ssh, 0x0009): tried: '/Library/Frameworks/ssh.framework/ssh' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Library/Frameworks/ssh.framework/ssh' (no such file), '/Library/Frameworks/ssh.framework/ssh' (no such file), '/System/Library/Frameworks/ssh.framework/ssh' (no such file, not in dyld cache)
dlopen(/System/Library/Frameworks/ssh.framework/ssh, 0x0009): tried: '/System/Library/Frameworks/ssh.framework/ssh' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/System/Library/Frameworks/ssh.framework/ssh' (no such file), '/System/Library/Frameworks/ssh.framework/ssh' (no such file, not in dyld cache), '/Library/Frameworks/ssh.framework/ssh' (no such file)
Native library (darwin-x86-64/libssh.dylib) not found in resource path (/Applications/Gitnuro.app/Contents/app/Gitnuro-1.2.1-adf9bda6d54d85d128a3629365e15ce.jar:/Applications/Gitnuro.app/Contents/app/JavaEWAH-1.1.13-a1eb305e5cc5bba238d436e3139abb4.jar:/Applications/Gitnuro.app/Contents/app/animation-core-desktop-1.4.0-25ebd61540c48128c99fa21682d931b1.jar:/Applications/Gitnuro.app/Contents/app/animation-desktop-1.4.0-661aa0e87f6d94530a3194d7168ad55.jar:/Applications/Gitnuro.app/Contents/app/annotations-13.0-f4fb462172517b46b6cd900358515a.jar:/Applications/Gitnuro.app/Contents/app/atomicfu-jvm-0.17.0-9031dba6d62a5163d26260e9d1bda7c.jar:/Applications/Gitnuro.app/Contents/app/bcpg-jdk18on-1.72-c99f8ee5aa2fee1e24d23306487b0d6.jar:/Applications/Gitnuro.app/Contents/app/bcpkix-jdk18on-1.72-4bb2ace2ca16e7fd42a0a0c13d17464.jar:/Applications/Gitnuro.app/Contents/app/bcprov-jdk18on-1.72-eb4ed3b81359fb50a828723a4a9ab0b6.jar:/Applications/Gitnuro.app/Contents/app/bcutil-jdk18on-1.72-cade3651656670f716a430c4e3899d93.jar:/Applications/Gitnuro.app/Contents/app/converter-scalars-2.9.0-6e2e258b8b91ce475cd6bb38b3419cb5.jar:/Applications/Gitnuro.app/Contents/app/dagger-2.45-dc9ea35108b1317ec9df96abd658c.jar:/Applications/Gitnuro.app/Contents/app/desktop-jvm-1.4.0-784169ffd75e9c895e9ca5f2959ad97f.jar:/Applications/Gitnuro.app/Contents/app/eddsa-0.3.0-ee7de3b6f19de76a6e465efc978f669.jar:/Applications/Gitnuro.app/Contents/app/foundation-desktop-1.4.0-674cca9abff0dbd666e7501896538721.jar:/Applications/Gitnuro.app/Contents/app/foundation-layout-desktop-1.4.0-12b0accbe72af3438e29c41654b594.jar:/Applications/Gitnuro.app/Contents/app/javax.inject-1-289075e48b909e9e74e6c915b3631d2e.jar:/Applications/Gitnuro.app/Contents/app/jcl-over-slf4j-1.7.32-8788169f5d5be655efc75d3bfffc82c.jar:/Applications/Gitnuro.app/Contents/app/jna-5.13.0-bd2e5bc6b4b020c2d9a6e17a8e9bcef1.jar:/Applications/Gitnuro.app/Contents/app/kotlin-logging-jvm-4.0.0-beta-27-fb2692544b551dee528f235407ddb.jar:/Applications/Gitnuro.app/Contents/app/kotlin-stdlib-1.8.20-2b3d65e24952649bf7534017c64b435e.jar:/Applications/Gitnuro.app/Contents/app/kotlin-stdlib-common-1.8.20-af45a8873880f027f47d573e1483a6dc.jar:/Applications/Gitnuro.app/Contents/app/kotlin-stdlib-jdk7-1.8.20-da3588af3bb0c9122dbae3d733dddf53.jar:/Applications/Gitnuro.app/Contents/app/kotlin-stdlib-jdk8-1.8.20-2097cb28602f5a6320bcc1bd74914db9.jar:/Applications/Gitnuro.app/Contents/app/kotlinx-coroutines-core-jvm-1.6.4-9ba1873872fe146d39bc46835c45.jar:/Applications/Gitnuro.app/Contents/app/kotlinx-serialization-core-jvm-1.5.0-7da2483af6578dd05bbb2011eb8ed494.jar:/Applications/Gitnuro.app/Contents/app/kotlinx-serialization-json-jvm-1.5.0-3e17f3672da94b78965bb22bd0605e15.jar:/Applications/Gitnuro.app/Contents/app/library-desktop-1.4.0-622e9f31b733339b7fcc539d3bf67fe6.jar:/Applications/Gitnuro.app/Contents/app/library-desktop-1.4.0-819b421bd73ce0b865c9126599de74.jar:/Applications/Gitnuro.app/Contents/app/library-desktop-1.4.0-e6d88ff436b8e23184b6db0d5e7dde9.jar:/Applications/Gitnuro.app/Contents/app/material-desktop-1.4.0-34596aefd4b1abb9571bb38fc53fe4e.jar:/Applications/Gitnuro.app/Contents/app/material-icons-core-desktop-1.4.0-223ee2d7472869a15f7ca96c2eb5b966.jar:/Applications/Gitnuro.app/Contents/app/material-ripple-desktop-1.4.0-14bdc0128ed534bbbccd24de9af8b3.jar:/Applications/Gitnuro.app/Contents/app/okhttp-3.14.9-69e22f2ccb614cf1bcfcca5cf7711045.jar:/Applications/Gitnuro.app/Contents/app/okio-1.17.2-54a6a8979bd8e64e1fbf21d511654737.jar:/Applications/Gitnuro.app/Contents/app/org.eclipse.jgit-6.5.0.202303070854-r-16136affece2a55ced413946fb2e5398.jar:/Applications/Gitnuro.app/Contents/app/org.eclipse.jgit.gpg.bc-6.5.0.202303070854-r-2fa04432fc6af82fd099d07a38155bdc.jar:/Applications/Gitnuro.app/Contents/app/reload4j-1.2.22-53e3301fc57f593f1683da8195364a14.jar:/Applications/Gitnuro.app/Contents/app/retrofit-2.9.0-89d951895e6d080185377c74152602.jar:/Applications/Gitnuro.app/Contents/app/runtime-desktop-1.4.0-31ed2d7f57c5c0b8fc3a768d416a22f.jar:/Applications/Gitnuro.app/Contents/app/runtime-saveable-desktop-1.4.0-539c50bdb18dbb348a0adb8fbd16b80.jar:/Applications/Gitnuro.app/Contents/app/skiko-awt-0.7.58-649f11561926cb7bbf9dcde23bb44dd4.jar:/Applications/Gitnuro.app/Contents/app/skiko-awt-runtime-macos-x64-0.7.58-b5f7fc8af326dbc15b639d8781d1ab.jar:/Applications/Gitnuro.app/Contents/app/slf4j-api-2.0.7-403dffa46cdd2e3c82da19df4f394a4c.jar:/Applications/Gitnuro.app/Contents/app/slf4j-reload4j-2.0.7-46103a7177ee22bfb3c2723651a7bccb.jar:/Applications/Gitnuro.app/Contents/app/sshd-common-2.9.0-40b96692e45f852ca973507529828c.jar:/Applications/Gitnuro.app/Contents/app/sshd-core-2.9.0-792851ff98cc1dfb7576deaac9bf68.jar:/Applications/Gitnuro.app/Contents/app/ui-desktop-1.4.0-7ad16cb90126163346ee42e63f1c8.jar:/Applications/Gitnuro.app/Contents/app/ui-geometry-desktop-1.4.0-d9bbc5c91cc85c97f4ceca4ca8d7f522.jar:/Applications/Gitnuro.app/Contents/app/ui-graphics-desktop-1.4.0-b629a32a9e8549db837ee1ec95837bc.jar:/Applications/Gitnuro.app/Contents/app/ui-text-desktop-1.4.0-a128dcc2a051dab2d38de9ac33fdd29.jar:/Applications/Gitnuro.app/Contents/app/ui-tooling-preview-desktop-1.4.0-90fb251bf3b78b5c6ef36ea9591a46f.jar:/Applications/Gitnuro.app/Contents/app/ui-unit-desktop-1.4.0-21513dd747103c5f2369198dab4fb7.jar:/Applications/Gitnuro.app/Contents/app/ui-util-desktop-1.4.0-b1d72a3f3f20bc84f56413199be16edb.jar)
	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:323)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:483)
	at com.sun.jna.Library$Handler.<init>(Library.java:197)
	at com.sun.jna.Native.load(Native.java:622)
	at com.sun.jna.Native.load(Native.java:596)
	at com.jetpackduba.gitnuro.ssh.libssh.SSHLibrary$Companion.<clinit>(LibSshWrapper.kt:42)
	at com.jetpackduba.gitnuro.ssh.libssh.SSHLibrary.<clinit>(LibSshWrapper.kt)
	at com.jetpackduba.gitnuro.ssh.libssh.LibSshSession.<init>(LibSshSession.kt:10)
	at com.jetpackduba.gitnuro.ssh.libssh.LibSshSession_Factory.newInstance(LibSshSession_Factory.java:33)
	at com.jetpackduba.gitnuro.ssh.libssh.LibSshSession_Factory.get(LibSshSession_Factory.java:25)
	at com.jetpackduba.gitnuro.ssh.libssh.LibSshSession_Factory.get(LibSshSession_Factory.java:9)
	at com.jetpackduba.gitnuro.credentials.GRemoteSession.setup(GRemoteSession.kt:38)
	at com.jetpackduba.gitnuro.credentials.GSessionManager$generateSshSessionFactory$1.getSession(GSessionManager.kt:23)
	at org.eclipse.jgit.transport.SshTransport.getSession(SshTransport.java:107)
	at org.eclipse.jgit.transport.TransportGitSsh$SshFetchConnection.<init>(TransportGitSsh.java:281)
	... 29 more
	Suppressed: java.lang.UnsatisfiedLinkError: dlopen(libssh.dylib, 0x0009): tried: 'libssh.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibssh.dylib' (no such file), '/usr/lib/libssh.dylib' (no such file, not in dyld cache), 'libssh.dylib' (no such file), '/usr/local/lib/libssh.dylib' (no such file), '/usr/lib/libssh.dylib' (no such file, not in dyld cache)
		at com.sun.jna.Native.open(Native Method)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:211)
		... 43 more
	Suppressed: java.lang.UnsatisfiedLinkError: dlopen(libssh.dylib, 0x0009): tried: 'libssh.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibssh.dylib' (no such file), '/usr/lib/libssh.dylib' (no such file, not in dyld cache), 'libssh.dylib' (no such file), '/usr/local/lib/libssh.dylib' (no such file), '/usr/lib/libssh.dylib' (no such file, not in dyld cache)
		at com.sun.jna.Native.open(Native Method)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:224)
		... 43 more
	Suppressed: java.lang.UnsatisfiedLinkError: dlopen(/Users/rdapp/Library/Frameworks/ssh.framework/ssh, 0x0009): tried: '/Users/rdapp/Library/Frameworks/ssh.framework/ssh' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/rdapp/Library/Frameworks/ssh.framework/ssh' (no such file), '/Users/rdapp/Library/Frameworks/ssh.framework/ssh' (no such file), '/Library/Frameworks/ssh.framework/ssh' (no such file), '/System/Library/Frameworks/ssh.framework/ssh' (no such file, not in dyld cache)
		at com.sun.jna.Native.open(Native Method)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:268)
		... 43 more
	Suppressed: java.lang.UnsatisfiedLinkError: dlopen(/Library/Frameworks/ssh.framework/ssh, 0x0009): tried: '/Library/Frameworks/ssh.framework/ssh' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Library/Frameworks/ssh.framework/ssh' (no such file), '/Library/Frameworks/ssh.framework/ssh' (no such file), '/System/Library/Frameworks/ssh.framework/ssh' (no such file, not in dyld cache)
		at com.sun.jna.Native.open(Native Method)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:268)
		... 43 more
	Suppressed: java.lang.UnsatisfiedLinkError: dlopen(/System/Library/Frameworks/ssh.framework/ssh, 0x0009): tried: '/System/Library/Frameworks/ssh.framework/ssh' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/System/Library/Frameworks/ssh.framework/ssh' (no such file), '/System/Library/Frameworks/ssh.framework/ssh' (no such file, not in dyld cache), '/Library/Frameworks/ssh.framework/ssh' (no such file)
		at com.sun.jna.Native.open(Native Method)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:268)
		... 43 more

```

**Comment by JetpackDuba** [comment] 2023-06-19 07:07
That's odd! I haven't got a mac os system to test right now. Does the same happen when installing Gitnuro from brew?

If you don't mind, can you open a new issue please?

**Comment by JetpackDuba** [comment] 2023-06-20 14:28
Nevermind about creating a new issue, it's probably the same as https://github.com/JetpackDuba/Gitnuro/issues/130

**Comment by rossjwaddell** [comment] 2023-08-28 06:12
Not sure if this is the same issue or a new one.
But I'm getting similar responses when trying to push/pull/clone repositories in AWS on Ubuntu 22.04.

Here is the error in the console/log (obfuscated the repo and region):


```2023-08-28 15:28:09 ERROR slf4j:16 - TabState - ssh://git-codecommit.REGION.amazonaws.com/v1/repos/repo1: remote hung up unexpectedly
org.eclipse.jgit.api.errors.TransportException: ssh://git-codecommit.REGION.amazonaws.com/v1/repos/repo1: remote hung up unexpectedly
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:249)
	at org.eclipse.jgit.api.PullCommand.call(PullCommand.java:266)
	at com.jetpackduba.gitnuro.git.remote_operations.PullBranchUseCase$invoke$2.invokeSuspend(PullBranchUseCase.kt:27)
	at com.jetpackduba.gitnuro.git.remote_operations.PullBranchUseCase$invoke$2.invoke(PullBranchUseCase.kt)
	at com.jetpackduba.gitnuro.git.remote_operations.PullBranchUseCase$invoke$2.invoke(PullBranchUseCase.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:169)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.jetpackduba.gitnuro.git.remote_operations.PullBranchUseCase.invoke(PullBranchUseCase.kt:15)
	at com.jetpackduba.gitnuro.viewmodels.MenuViewModel$pull$1.invokeSuspend(MenuViewModel.kt:35)
	at com.jetpackduba.gitnuro.viewmodels.MenuViewModel$pull$1.invoke(MenuViewModel.kt)
	at com.jetpackduba.gitnuro.viewmodels.MenuViewModel$pull$1.invoke(MenuViewModel.kt)
	at com.jetpackduba.gitnuro.git.TabState$safeProcessing$job$1$2.invokeSuspend(TabState.kt:131)
	at com.jetpackduba.gitnuro.git.TabState$safeProcessing$job$1$2.invoke(TabState.kt)
	at com.jetpackduba.gitnuro.git.TabState$safeProcessing$job$1$2.invoke(TabState.kt)
	at com.jetpackduba.gitnuro.extensions.StateManagementUtilsKt.delayedStateChange(StateManagementUtils.kt:21)
	at com.jetpackduba.gitnuro.git.TabState$safeProcessing$job$1.invokeSuspend(TabState.kt:119)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: org.eclipse.jgit.errors.TransportException: ssh://git-codecommit.REGION.amazonaws.com/v1/repos/repo1: remote hung up unexpectedly
	at org.eclipse.jgit.transport.TransportGitSsh$SshFetchConnection.<init>(TransportGitSsh.java:313)
	at org.eclipse.jgit.transport.TransportGitSsh.openFetch(TransportGitSsh.java:153)
	at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:153)
	at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:105)
	at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1462)
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:238)
	... 24 more
Caused by: java.lang.NullPointerException: uri.user must not be null
	at com.jetpackduba.gitnuro.credentials.GRemoteSession.setup(GRemoteSession.kt:40)
	at com.jetpackduba.gitnuro.credentials.GSessionManager$generateSshSessionFactory$1.getSession(GSessionManager.kt:23)
	at org.eclipse.jgit.transport.SshTransport.getSession(SshTransport.java:107)
	at org.eclipse.jgit.transport.TransportGitSsh$SshFetchConnection.<init>(TransportGitSsh.java:281)
	... 29 more
2023-08-28 15:28:09 INFO  slf4j:8 - TabViewModel - Refreshing repository state SAFE

```

I saw you asking about .ssh/config file. Here is mine obfuscated:

```
Host tcp://IP:PORT
  HostName tcp://IP:PORT

Host git-codecommit.*.amazonaws.com
  User AWS_USER
  IdentityFile ~/.ssh/RSA_KEY
```

**Comment by JetpackDuba** [comment] 2023-08-28 08:54
Hey @rossjwaddell ! 

This is the main issue `Caused by: java.lang.NullPointerException: uri.user must not be null`. I've just pushed a fix and will be released with the next version.
